### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by emad-elsaid** [interactive-pioneers/capistrano-docker-compose#16]
I was reading the gemspec file and found that you added `rspec` and `rake` and `bundler` as development dependency, i have 3 questions for each :
- why rspec as we didn't write any tests for the gem
- also why rake? we already added capistrano which depends on rake by default, adding rake may result in conflict in the future right?
- why bundler? we already added capistrano dependency and it include bundler by default, right?

**Comment by ain** [comment]
@blazeeboy you're right, the dependencies should get a 2nd look. 

Closing the topic as optimisation ticket exists.

Thanks for feedback!
